name: ishapp
description: Flutter app for jumush

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+21
  http: ^0.12.2
  path_provider: ^1.6.27


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1             # This plugin help us to use custom svg icons
  carousel_pro: ^1.0.0             # This plugin help us to display user profile images in carousel style
  flutter_launcher_icons: ^0.7.5   # Used to generate app icon launcher for both platforms android and iOS
  swipe_stack: ^1.0.0              # Used to Swipe User Profiles like tinder cards
  flutter_datetime_picker: ^1.4.0  # Used to Select Date Time - (here used especially for User Birthday)
  country_code_picker: ^1.4.0      # Used to Select User Country Code
  otp_screen: ^0.0.3               # Screen Used to Validate OTP sent to user device (SMS Code Verification)

dev_dependencies:
  flutter_test:
    sdk: flutter
  easy_localization: ^2.3.2
  shared_preferences: ^0.5.6
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  flutter_boxicons: ^2.0.2
  multiselect_formfield: ^0.1.5
  flutter_staggered_animations: ^0.1.2
  flutter_tindercard: ^0.2.0
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  redux_dev_tools: ^0.4.0
  flutter_redux_dev_tools: ^0.3.0
  redux_api_middleware: ^0.1.9
  redux_thunk: ^0.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: GTEestiProDisplay
      fonts:
        - asset: assets/fonts/GTEestiProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/GTEestiProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/GTEestiProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/GTEestiProDisplay-Bold.ttf
          weight: 700
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/images/demo_users/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

     # For details regarding fonts from package dependencies,
     # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
